package org.bytestorm.bitesync.localization

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val code: String, val nativeName: String, val flag: String) {
    ENGLISH("en", "English", "\uD83C\uDDEC\uD83C\uDDE7"),
    ROMANIAN("ro", "Română", "\uD83C\uDDF7\uD83C\uDDF4"),
    SPANISH("es", "Español", "\uD83C\uDDEA\uD83C\uDDF8"),
    FRENCH("fr", "Français", "\uD83C\uDDEB\uD83C\uDDF7"),
    GERMAN("de", "Deutsch", "\uD83C\uDDE9\uD83C\uDDEA"),
    PORTUGUESE("pt", "Português", "\uD83C\uDDE7\uD83C\uDDF7"),
    ITALIAN("it", "Italiano", "\uD83C\uDDEE\uD83C\uDDF9"),
    JAPANESE("ja", "日本語", "\uD83C\uDDEF\uD83C\uDDF5"),
    CHINESE("zh", "中文", "\uD83C\uDDE8\uD83C\uDDF3"),
    KOREAN("ko", "한국어", "\uD83C\uDDF0\uD83C\uDDF7");

    companion object {
        fun fromCode(code: String): AppLanguage =
            entries.find { it.code == code } ?: ENGLISH
    }
}

data class AppStrings(
    // App
    val tagline: String,

    // Lobby
    val createRoom: String,
    val joinRoom: String,
    val yourName: String,
    val roomPin: String,
    val pickRestaurants: String,
    val waitingForPlayers: String,
    val playersCount: (Int) -> String,

    // Suggest
    val addRestaurants: String,
    val roomInfo: (String, Int) -> String,
    val searchPlaceholder: String,
    val addedCount: (Int) -> String,
    val readyToSwipe: String,
    val searchAndAdd: String,
    val everyoneCanContribute: String,
    val readyStatus: (Int, Int) -> String,
    val ready: String,
    val imReady: String,
    val addAtLeast2: String,

    // Swipe
    val swiping: String,
    val roomUsers: (String, Int) -> String,
    val like: String,
    val nope: String,
    val noMoreVenues: String,
    val waitingForMatch: String,

    // Sudden Death
    val suddenDeath: String,
    val roundNumber: (Int) -> String,
    val restaurantsRemain: (Int) -> String,
    val roundPlayers: (Int, Int) -> String,

    // Match
    val itsAMatch: String,
    val randomlyChosen: String,
    val everyoneAgreed: String,
    val openMaps: String,
    val backToLobby: String,

    // Settings
    val settings: String,
    val appearance: String,
    val systemDefault: String,
    val light: String,
    val dark: String,
    val language: String,
)

val LocalStrings = compositionLocalOf { englishStrings }

fun stringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.ENGLISH -> englishStrings
    AppLanguage.ROMANIAN -> romanianStrings
    AppLanguage.SPANISH -> spanishStrings
    AppLanguage.FRENCH -> frenchStrings
    AppLanguage.GERMAN -> germanStrings
    AppLanguage.PORTUGUESE -> portugueseStrings
    AppLanguage.ITALIAN -> italianStrings
    AppLanguage.JAPANESE -> japaneseStrings
    AppLanguage.CHINESE -> chineseStrings
    AppLanguage.KOREAN -> koreanStrings
}

// region English
val englishStrings = AppStrings(
    tagline = "Swipe together. Eat together.",
    createRoom = "Create Room",
    joinRoom = "Join Room",
    yourName = "Your Name",
    roomPin = "Room PIN",
    pickRestaurants = "Pick Restaurants!",
    waitingForPlayers = "Waiting for more players…",
    playersCount = { "Players ($it)" },
    addRestaurants = "Add Restaurants",
    roomInfo = { pin, n -> "Room: $pin · $n players" },
    searchPlaceholder = "Search for a restaurant…",
    addedCount = { "Added ($it)" },
    readyToSwipe = "Ready to swipe!",
    searchAndAdd = "Search and add restaurants above",
    everyoneCanContribute = "Everyone can contribute!",
    readyStatus = { r, t -> "$r/$t ready" },
    ready = "Ready!",
    imReady = "I'm Ready",
    addAtLeast2 = "Add at least 2 restaurants to be ready",
    swiping = "Swiping",
    roomUsers = { pin, n -> "Room: $pin · $n users" },
    like = "LIKE",
    nope = "NOPE",
    noMoreVenues = "No more venues!",
    waitingForMatch = "Waiting for a match…",
    suddenDeath = "SUDDEN DEATH",
    roundNumber = { "Round $it" },
    restaurantsRemain = { "$it restaurants remain…" },
    roundPlayers = { r, p -> "Round $r · $p players" },
    itsAMatch = "It's a Match!",
    randomlyChosen = "Randomly chosen:",
    everyoneAgreed = "Everyone agreed on",
    openMaps = "Open Maps",
    backToLobby = "Back to Lobby",
    settings = "Settings",
    appearance = "Appearance",
    systemDefault = "System",
    light = "Light",
    dark = "Dark",
    language = "Language",
)
// endregion

// region Romanian
val romanianStrings = AppStrings(
    tagline = "Glisați împreună. Mâncați împreună.",
    createRoom = "Creează Cameră",
    joinRoom = "Intră în Cameră",
    yourName = "Numele Tău",
    roomPin = "PIN Cameră",
    pickRestaurants = "Alege Restaurante!",
    waitingForPlayers = "Se așteaptă mai mulți jucători…",
    playersCount = { "Jucători ($it)" },
    addRestaurants = "Adaugă Restaurante",
    roomInfo = { pin, n -> "Cameră: $pin · $n jucători" },
    searchPlaceholder = "Caută un restaurant…",
    addedCount = { "Adăugate ($it)" },
    readyToSwipe = "Gata de swipe!",
    searchAndAdd = "Caută și adaugă restaurante mai sus",
    everyoneCanContribute = "Toți pot contribui!",
    readyStatus = { r, t -> "$r/$t pregătiți" },
    ready = "Pregătit!",
    imReady = "Sunt Pregătit",
    addAtLeast2 = "Adaugă cel puțin 2 restaurante",
    swiping = "Glisare",
    roomUsers = { pin, n -> "Cameră: $pin · $n utilizatori" },
    like = "DA",
    nope = "NU",
    noMoreVenues = "Nu mai sunt locuri!",
    waitingForMatch = "Se așteaptă potrivirea…",
    suddenDeath = "MOARTE SUBITĂ",
    roundNumber = { "Runda $it" },
    restaurantsRemain = { "$it restaurante rămase…" },
    roundPlayers = { r, p -> "Runda $r · $p jucători" },
    itsAMatch = "Este o Potrivire!",
    randomlyChosen = "Ales aleatoriu:",
    everyoneAgreed = "Toți au fost de acord cu",
    openMaps = "Deschide Harta",
    backToLobby = "Înapoi la Lobby",
    settings = "Setări",
    appearance = "Aspect",
    systemDefault = "Sistem",
    light = "Luminos",
    dark = "Întunecat",
    language = "Limbă",
)
// endregion

// region Spanish
val spanishStrings = AppStrings(
    tagline = "Desliza juntos. Come juntos.",
    createRoom = "Crear Sala",
    joinRoom = "Unirse a Sala",
    yourName = "Tu Nombre",
    roomPin = "PIN de Sala",
    pickRestaurants = "¡Elige Restaurantes!",
    waitingForPlayers = "Esperando más jugadores…",
    playersCount = { "Jugadores ($it)" },
    addRestaurants = "Agregar Restaurantes",
    roomInfo = { pin, n -> "Sala: $pin · $n jugadores" },
    searchPlaceholder = "Buscar un restaurante…",
    addedCount = { "Agregados ($it)" },
    readyToSwipe = "¡Listos para deslizar!",
    searchAndAdd = "Busca y agrega restaurantes arriba",
    everyoneCanContribute = "¡Todos pueden contribuir!",
    readyStatus = { r, t -> "$r/$t listos" },
    ready = "¡Listo!",
    imReady = "Estoy Listo",
    addAtLeast2 = "Agrega al menos 2 restaurantes",
    swiping = "Deslizando",
    roomUsers = { pin, n -> "Sala: $pin · $n usuarios" },
    like = "SÍ",
    nope = "NO",
    noMoreVenues = "¡No hay más lugares!",
    waitingForMatch = "Esperando coincidencia…",
    suddenDeath = "MUERTE SÚBITA",
    roundNumber = { "Ronda $it" },
    restaurantsRemain = { "$it restaurantes quedan…" },
    roundPlayers = { r, p -> "Ronda $r · $p jugadores" },
    itsAMatch = "¡Es una Coincidencia!",
    randomlyChosen = "Elegido al azar:",
    everyoneAgreed = "Todos estuvieron de acuerdo en",
    openMaps = "Abrir Mapa",
    backToLobby = "Volver al Lobby",
    settings = "Ajustes",
    appearance = "Apariencia",
    systemDefault = "Sistema",
    light = "Claro",
    dark = "Oscuro",
    language = "Idioma",
)
// endregion

// region French
val frenchStrings = AppStrings(
    tagline = "Swipez ensemble. Mangez ensemble.",
    createRoom = "Créer une Salle",
    joinRoom = "Rejoindre une Salle",
    yourName = "Votre Nom",
    roomPin = "PIN de Salle",
    pickRestaurants = "Choisir des Restaurants !",
    waitingForPlayers = "En attente de joueurs…",
    playersCount = { "Joueurs ($it)" },
    addRestaurants = "Ajouter des Restaurants",
    roomInfo = { pin, n -> "Salle : $pin · $n joueurs" },
    searchPlaceholder = "Rechercher un restaurant…",
    addedCount = { "Ajoutés ($it)" },
    readyToSwipe = "Prêt à swiper !",
    searchAndAdd = "Cherchez et ajoutez des restaurants ci-dessus",
    everyoneCanContribute = "Tout le monde peut contribuer !",
    readyStatus = { r, t -> "$r/$t prêts" },
    ready = "Prêt !",
    imReady = "Je suis Prêt",
    addAtLeast2 = "Ajoutez au moins 2 restaurants",
    swiping = "En cours",
    roomUsers = { pin, n -> "Salle : $pin · $n utilisateurs" },
    like = "OUI",
    nope = "NON",
    noMoreVenues = "Plus de restaurants !",
    waitingForMatch = "En attente d'un match…",
    suddenDeath = "MORT SUBITE",
    roundNumber = { "Manche $it" },
    restaurantsRemain = { "$it restaurants restants…" },
    roundPlayers = { r, p -> "Manche $r · $p joueurs" },
    itsAMatch = "C'est un Match !",
    randomlyChosen = "Choisi au hasard :",
    everyoneAgreed = "Tout le monde est d'accord sur",
    openMaps = "Ouvrir la Carte",
    backToLobby = "Retour au Lobby",
    settings = "Paramètres",
    appearance = "Apparence",
    systemDefault = "Système",
    light = "Clair",
    dark = "Sombre",
    language = "Langue",
)
// endregion

// region German
val germanStrings = AppStrings(
    tagline = "Zusammen swipen. Zusammen essen.",
    createRoom = "Raum Erstellen",
    joinRoom = "Raum Beitreten",
    yourName = "Dein Name",
    roomPin = "Raum-PIN",
    pickRestaurants = "Restaurants Wählen!",
    waitingForPlayers = "Warte auf weitere Spieler…",
    playersCount = { "Spieler ($it)" },
    addRestaurants = "Restaurants Hinzufügen",
    roomInfo = { pin, n -> "Raum: $pin · $n Spieler" },
    searchPlaceholder = "Restaurant suchen…",
    addedCount = { "Hinzugefügt ($it)" },
    readyToSwipe = "Bereit zum Swipen!",
    searchAndAdd = "Suche und füge oben Restaurants hinzu",
    everyoneCanContribute = "Jeder kann beitragen!",
    readyStatus = { r, t -> "$r/$t bereit" },
    ready = "Bereit!",
    imReady = "Ich bin Bereit",
    addAtLeast2 = "Füge mindestens 2 Restaurants hinzu",
    swiping = "Swipen",
    roomUsers = { pin, n -> "Raum: $pin · $n Nutzer" },
    like = "JA",
    nope = "NEIN",
    noMoreVenues = "Keine weiteren Restaurants!",
    waitingForMatch = "Warte auf ein Match…",
    suddenDeath = "SUDDEN DEATH",
    roundNumber = { "Runde $it" },
    restaurantsRemain = { "$it Restaurants übrig…" },
    roundPlayers = { r, p -> "Runde $r · $p Spieler" },
    itsAMatch = "Es ist ein Match!",
    randomlyChosen = "Zufällig gewählt:",
    everyoneAgreed = "Alle waren sich einig über",
    openMaps = "Karte Öffnen",
    backToLobby = "Zurück zur Lobby",
    settings = "Einstellungen",
    appearance = "Darstellung",
    systemDefault = "System",
    light = "Hell",
    dark = "Dunkel",
    language = "Sprache",
)
// endregion

// region Portuguese
val portugueseStrings = AppStrings(
    tagline = "Deslize juntos. Comam juntos.",
    createRoom = "Criar Sala",
    joinRoom = "Entrar na Sala",
    yourName = "Seu Nome",
    roomPin = "PIN da Sala",
    pickRestaurants = "Escolher Restaurantes!",
    waitingForPlayers = "Aguardando mais jogadores…",
    playersCount = { "Jogadores ($it)" },
    addRestaurants = "Adicionar Restaurantes",
    roomInfo = { pin, n -> "Sala: $pin · $n jogadores" },
    searchPlaceholder = "Buscar um restaurante…",
    addedCount = { "Adicionados ($it)" },
    readyToSwipe = "Pronto para deslizar!",
    searchAndAdd = "Pesquise e adicione restaurantes acima",
    everyoneCanContribute = "Todos podem contribuir!",
    readyStatus = { r, t -> "$r/$t prontos" },
    ready = "Pronto!",
    imReady = "Estou Pronto",
    addAtLeast2 = "Adicione pelo menos 2 restaurantes",
    swiping = "Deslizando",
    roomUsers = { pin, n -> "Sala: $pin · $n usuários" },
    like = "SIM",
    nope = "NÃO",
    noMoreVenues = "Sem mais restaurantes!",
    waitingForMatch = "Aguardando combinação…",
    suddenDeath = "MORTE SÚBITA",
    roundNumber = { "Rodada $it" },
    restaurantsRemain = { "$it restaurantes restantes…" },
    roundPlayers = { r, p -> "Rodada $r · $p jogadores" },
    itsAMatch = "É uma Combinação!",
    randomlyChosen = "Escolhido aleatoriamente:",
    everyoneAgreed = "Todos concordaram com",
    openMaps = "Abrir Mapa",
    backToLobby = "Voltar ao Lobby",
    settings = "Configurações",
    appearance = "Aparência",
    systemDefault = "Sistema",
    light = "Claro",
    dark = "Escuro",
    language = "Idioma",
)
// endregion

// region Italian
val italianStrings = AppStrings(
    tagline = "Scorri insieme. Mangia insieme.",
    createRoom = "Crea Stanza",
    joinRoom = "Unisciti alla Stanza",
    yourName = "Il Tuo Nome",
    roomPin = "PIN Stanza",
    pickRestaurants = "Scegli i Ristoranti!",
    waitingForPlayers = "In attesa di altri giocatori…",
    playersCount = { "Giocatori ($it)" },
    addRestaurants = "Aggiungi Ristoranti",
    roomInfo = { pin, n -> "Stanza: $pin · $n giocatori" },
    searchPlaceholder = "Cerca un ristorante…",
    addedCount = { "Aggiunti ($it)" },
    readyToSwipe = "Pronti a scorrere!",
    searchAndAdd = "Cerca e aggiungi ristoranti sopra",
    everyoneCanContribute = "Tutti possono contribuire!",
    readyStatus = { r, t -> "$r/$t pronti" },
    ready = "Pronto!",
    imReady = "Sono Pronto",
    addAtLeast2 = "Aggiungi almeno 2 ristoranti",
    swiping = "Scorrimento",
    roomUsers = { pin, n -> "Stanza: $pin · $n utenti" },
    like = "SÌ",
    nope = "NO",
    noMoreVenues = "Nessun altro ristorante!",
    waitingForMatch = "In attesa di un match…",
    suddenDeath = "MORTE IMPROVVISA",
    roundNumber = { "Round $it" },
    restaurantsRemain = { "$it ristoranti rimasti…" },
    roundPlayers = { r, p -> "Round $r · $p giocatori" },
    itsAMatch = "È un Match!",
    randomlyChosen = "Scelto a caso:",
    everyoneAgreed = "Tutti d'accordo su",
    openMaps = "Apri Mappa",
    backToLobby = "Torna alla Lobby",
    settings = "Impostazioni",
    appearance = "Aspetto",
    systemDefault = "Sistema",
    light = "Chiaro",
    dark = "Scuro",
    language = "Lingua",
)
// endregion

// region Japanese
val japaneseStrings = AppStrings(
    tagline = "一緒にスワイプ。一緒に食べよう。",
    createRoom = "ルームを作成",
    joinRoom = "ルームに参加",
    yourName = "あなたの名前",
    roomPin = "ルームPIN",
    pickRestaurants = "レストランを選ぼう！",
    waitingForPlayers = "他のプレイヤーを待っています…",
    playersCount = { "プレイヤー ($it)" },
    addRestaurants = "レストランを追加",
    roomInfo = { pin, n -> "ルーム: $pin · ${n}人" },
    searchPlaceholder = "レストランを検索…",
    addedCount = { "追加済み ($it)" },
    readyToSwipe = "スワイプ準備完了！",
    searchAndAdd = "上でレストランを検索して追加",
    everyoneCanContribute = "みんなで追加できます！",
    readyStatus = { r, t -> "$r/$t 準備完了" },
    ready = "準備完了！",
    imReady = "準備OK",
    addAtLeast2 = "2つ以上のレストランを追加してください",
    swiping = "スワイプ中",
    roomUsers = { pin, n -> "ルーム: $pin · ${n}人" },
    like = "いいね",
    nope = "パス",
    noMoreVenues = "もうレストランがありません！",
    waitingForMatch = "マッチを待っています…",
    suddenDeath = "サドンデス",
    roundNumber = { "ラウンド $it" },
    restaurantsRemain = { "${it}軒が残っています…" },
    roundPlayers = { r, p -> "ラウンド $r · ${p}人" },
    itsAMatch = "マッチしました！",
    randomlyChosen = "ランダムに選ばれました：",
    everyoneAgreed = "全員一致：",
    openMaps = "マップを開く",
    backToLobby = "ロビーに戻る",
    settings = "設定",
    appearance = "外観",
    systemDefault = "システム",
    light = "ライト",
    dark = "ダーク",
    language = "言語",
)
// endregion

// region Chinese
val chineseStrings = AppStrings(
    tagline = "一起滑动，一起用餐。",
    createRoom = "创建房间",
    joinRoom = "加入房间",
    yourName = "你的名字",
    roomPin = "房间PIN码",
    pickRestaurants = "选择餐厅！",
    waitingForPlayers = "等待更多玩家…",
    playersCount = { "玩家 ($it)" },
    addRestaurants = "添加餐厅",
    roomInfo = { pin, n -> "房间: $pin · ${n}名玩家" },
    searchPlaceholder = "搜索餐厅…",
    addedCount = { "已添加 ($it)" },
    readyToSwipe = "准备滑动！",
    searchAndAdd = "在上方搜索并添加餐厅",
    everyoneCanContribute = "每个人都可以贡献！",
    readyStatus = { r, t -> "$r/$t 已准备" },
    ready = "已准备！",
    imReady = "我准备好了",
    addAtLeast2 = "请至少添加2家餐厅",
    swiping = "滑动中",
    roomUsers = { pin, n -> "房间: $pin · ${n}名用户" },
    like = "喜欢",
    nope = "不要",
    noMoreVenues = "没有更多餐厅了！",
    waitingForMatch = "等待匹配…",
    suddenDeath = "突然死亡",
    roundNumber = { "第${it}轮" },
    restaurantsRemain = { "还剩${it}家餐厅…" },
    roundPlayers = { r, p -> "第${r}轮 · ${p}名玩家" },
    itsAMatch = "匹配成功！",
    randomlyChosen = "随机选择：",
    everyoneAgreed = "大家都同意：",
    openMaps = "打开地图",
    backToLobby = "返回大厅",
    settings = "设置",
    appearance = "外观",
    systemDefault = "跟随系统",
    light = "浅色",
    dark = "深色",
    language = "语言",
)
// endregion

// region Korean
val koreanStrings = AppStrings(
    tagline = "함께 스와이프. 함께 먹자.",
    createRoom = "방 만들기",
    joinRoom = "방 참가",
    yourName = "이름",
    roomPin = "방 PIN",
    pickRestaurants = "맛집 고르기!",
    waitingForPlayers = "다른 플레이어를 기다리는 중…",
    playersCount = { "플레이어 ($it)" },
    addRestaurants = "맛집 추가",
    roomInfo = { pin, n -> "방: $pin · ${n}명" },
    searchPlaceholder = "맛집 검색…",
    addedCount = { "추가됨 ($it)" },
    readyToSwipe = "스와이프 준비 완료!",
    searchAndAdd = "위에서 맛집을 검색하고 추가하세요",
    everyoneCanContribute = "모두 추가할 수 있어요!",
    readyStatus = { r, t -> "$r/$t 준비 완료" },
    ready = "준비 완료!",
    imReady = "준비됨",
    addAtLeast2 = "최소 2개의 맛집을 추가하세요",
    swiping = "스와이프 중",
    roomUsers = { pin, n -> "방: $pin · ${n}명" },
    like = "좋아요",
    nope = "싫어요",
    noMoreVenues = "더 이상 맛집이 없습니다!",
    waitingForMatch = "매치를 기다리는 중…",
    suddenDeath = "서든데스",
    roundNumber = { "라운드 $it" },
    restaurantsRemain = { "${it}개 맛집 남음…" },
    roundPlayers = { r, p -> "라운드 $r · ${p}명" },
    itsAMatch = "매치 성공!",
    randomlyChosen = "랜덤 선택:",
    everyoneAgreed = "모두 동의:",
    openMaps = "지도 열기",
    backToLobby = "로비로 돌아가기",
    settings = "설정",
    appearance = "테마",
    systemDefault = "시스템",
    light = "라이트",
    dark = "다크",
    language = "언어",
)
// endregion
